; PlatformIO Project Configuration File — ESP-FC (buildable)
; Build:        pio run -e esp32
; Build+flash:  pio run -e esp32 -t upload
; Serial mon:   pio device monitor

[platformio]
default_envs = esp32

[env]
build_flags =
  -std=gnu++17
  -Wall
  -Wdouble-promotion
build_unflags =
  -std=gnu++11
  -ggdb
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
lib_deps =
  yoursunny/WifiEspNow @ ^0.0.20230713
  https://github.com/rtlopez/espnow-rclink/archive/refs/tags/v0.1.1.zip

[env:esp32]
board = lolin32
platform = espressif32@7.0.1
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = partitions_4M_nota.csv
lib_deps = ${env.lib_deps}
build_unflags = ${env.build_unflags}
build_flags = ${env.build_flags}

[env:esp32s3]
board = lolin_s3_mini
platform = espressif32@7.0.1
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = partitions_4M_nota.csv
lib_deps = ${env.lib_deps}
build_unflags =
  ${env.build_unflags}
  -DBOARD_HAS_PSRAM
build_flags =
  ${env.build_flags}
  -DESP32S3
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
board_upload.use_1200bps_touch = yes
board_upload.wait_for_upload_port = yes
board_upload.require_upload_port = yes

[env:esp32s2]
board = esp32-s2-saola-1
platform = espressif32@7.0.1
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = partitions_4M_nota.csv
lib_deps = ${env.lib_deps}
build_unflags = ${env.build_unflags}
build_flags =
  ${env.build_flags}
  -DESP32S2
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=1
board_upload.use_1200bps_touch = yes
board_upload.wait_for_upload_port = yes
board_upload.require_upload_port = yes

[env:esp32c3]
board = esp32-c3-devkitm-1
platform = espressif32@7.0.1
framework = arduino
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
lib_deps = ${env.lib_deps}
build_unflags = ${env.build_unflags}
build_flags =
  ${env.build_flags}
  -DESP32C3
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
